@echo off
REM ****************************************************************************
REM Vivado (TM) v2022.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Mon May 04 19:23:52 +0300 2026
REM SW Build 3526262 on Mon Apr 18 15:48:16 MDT 2022
REM
REM IP Build 3524634 on Mon Apr 18 20:55:01 MDT 2022
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim tb_table_sort_behav -key {Behavioral:sim_1:Functional:tb_table_sort} -tclbatch tb_table_sort.tcl -view C:/LRMLD/module_library/table_sort/tb_sml_list_sort_behav.wcfg -log simulate.log"
call xsim  tb_table_sort_behav -key {Behavioral:sim_1:Functional:tb_table_sort} -tclbatch tb_table_sort.tcl -view C:/LRMLD/module_library/table_sort/tb_sml_list_sort_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
