# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "C:/LRMLD/decoders/RM_16_11/RM_16_11.runs/synth_1/wp_top.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "synth_1" START { ROLLUP_AUTO }
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xcku035-fbva676-1-i

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/LRMLD/decoders/RM_16_11/RM_16_11.cache/wt [current_project]
set_property parent.project_path C:/LRMLD/decoders/RM_16_11/RM_16_11.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/LRMLD/decoders/RM_16_11/RM_16_11.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_verilog -library xil_defaultlib -sv {
  C:/LRMLD/module_library/all_modules/bitonic_merge_4_4_ir.sv
  C:/LRMLD/module_library/all_modules/bitonic_merge_8_8_ir.sv
  C:/LRMLD/module_library/all_modules/bitonic_sort_fp.sv
  C:/LRMLD/module_library/all_modules/cas.sv
  C:/LRMLD/module_library/all_modules/cas_l.sv
  C:/LRMLD/module_library/all_modules/comb.sv
  C:/LRMLD/module_library/all_modules/comparator.sv
  C:/LRMLD/module_library/all_modules/delay_line.sv
  C:/LRMLD/module_library/all_modules/full_sum_lists.sv
  C:/LRMLD/module_library/all_modules/list_delay.sv
  C:/LRMLD/module_library/all_modules/make.sv
  C:/LRMLD/module_library/all_modules/merge_2n_n.sv
  C:/LRMLD/module_library/all_modules/merge_tree.sv
  C:/LRMLD/module_library/all_modules/min2_frm5.sv
  C:/LRMLD/module_library/all_modules/min_3_frm_7.sv
  C:/LRMLD/module_library/all_modules/n_adder.sv
  C:/LRMLD/module_library/all_modules/sml_lists_sort.sv
  C:/LRMLD/module_library/all_modules/sort_2.sv
  C:/LRMLD/module_library/all_modules/sort_4.sv
  C:/LRMLD/module_library/all_modules/sort_8.sv
  C:/LRMLD/module_library/all_modules/sum_select.sv
  C:/LRMLD/module_library/all_modules/sum_select8.sv
  C:/LRMLD/module_library/all_modules/sum_select_12_bm_ir.sv
  C:/LRMLD/module_library/all_modules/sum_select_16_bm_ir.sv
  C:/LRMLD/module_library/all_modules/sum_select_8.sv
  C:/LRMLD/module_library/all_modules/table_sort.sv
  C:/LRMLD/decoders/RM_16_11/RM_16_11.srcs/sources_1/new/top.sv
  C:/LRMLD/module_library/all_modules/top_comb.sv
  C:/LRMLD/module_library/all_modules/unite_lists.sv
  C:/LRMLD/decoders/RM_16_11/RM_16_11.srcs/sources_1/new/wp_top.sv
}
OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/LRMLD/module_library/all_modules/constraints.xdc
set_property used_in_implementation false [get_files C:/LRMLD/module_library/all_modules/constraints.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top wp_top -part xcku035-fbva676-1-i
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef wp_top.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "synth_1_synth_report_utilization_0" "report_utilization -file wp_top_utilization_synth.rpt -pb wp_top_utilization_synth.pb"
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
